"""MudraDatabase with 28 Asamyuta and 24 Samyuta hastas."""
from __future__ import annotations
from ..models import Mudra, MudraType


class MudraDatabase:
    """Complete database of classical dance hand gestures (hastas)."""

    def __init__(self) -> None:
        self._mudras: list[Mudra] = self._load_asamyuta() + self._load_samyuta()

    def _load_asamyuta(self) -> list[Mudra]:
        """28 Asamyuta (single-hand) hastas from Natyashastra."""
        return [
            Mudra(name="Pataka", sanskrit_name="Pataka", mudra_type=MudraType.ASAMYUTA,
                  description="Flag - all fingers extended and joined, thumb bent",
                  fingers="All fingers extended together, thumb bent against palm",
                  usage=["cloud", "forest", "bosom", "night", "river", "horse", "cutting"],
                  viniyoga="Used to denote clouds, forest, forbidding, bosom, night, river, world of gods, horse, cutting, wind, reclining, walking, prowess, grace, moonlight, strong sunlight, knocking, waves, entering a street, equality, applying sandal paste, blessing, addressing, the sea, sword, month"),
            Mudra(name="Tripataka", sanskrit_name="Tripataka", mudra_type=MudraType.ASAMYUTA,
                  description="Three-flag - ring finger bent, rest extended",
                  fingers="Ring finger bent, other fingers extended and joined",
                  usage=["crown", "tree", "lamp", "fire", "pigeon"],
                  viniyoga="Used to denote crown, tree, Indra's thunderbolt, lamp, fire, pigeon"),
            Mudra(name="Ardhapataka", sanskrit_name="Ardhapataka", mudra_type=MudraType.ASAMYUTA,
                  description="Half-flag - little finger and ring finger bent",
                  fingers="Little and ring fingers bent, others extended",
                  usage=["leaves", "writing", "knife", "tower", "horn"],
                  viniyoga="Used for leaves, writing, knife edge, tower, bank of river"),
            Mudra(name="Kartarimukha", sanskrit_name="Kartarimukha", mudra_type=MudraType.ASAMYUTA,
                  description="Scissors - index and middle fingers spread like scissors",
                  fingers="Index and middle spread apart, ring and little closed, thumb bent",
                  usage=["separation", "lightning", "falling", "creeper"],
                  viniyoga="Used for separation of man and woman, opposition, corner of eye, death, disagreement, lightning"),
            Mudra(name="Mayura", sanskrit_name="Mayura", mudra_type=MudraType.ASAMYUTA,
                  description="Peacock - ring finger and thumb touch, others extended",
                  fingers="Ring finger tip touches thumb tip, others extended and spread",
                  usage=["peacock", "bird", "vomiting", "forehead mark"],
                  viniyoga="Used for peacock, famed bird, vomiting, tilaka on forehead"),
            Mudra(name="Ardhachandra", sanskrit_name="Ardhachandra", mudra_type=MudraType.ASAMYUTA,
                  description="Half-moon - from Pataka, thumb stretched out",
                  fingers="All fingers extended, thumb stretched sideways (from Pataka)",
                  usage=["moon", "waist", "anxiety", "meditation", "prayer"],
                  viniyoga="Used for moon, waist, hand of an image, anxiety, greeting, meditation"),
            Mudra(name="Arala", sanskrit_name="Arala", mudra_type=MudraType.ASAMYUTA,
                  description="Bent - index finger bent, rest extended",
                  fingers="Index finger bent, other fingers extended and spread",
                  usage=["drinking nectar", "strong wind", "beauty"],
                  viniyoga="Used for drinking poison, nectar, breeze"),
            Mudra(name="Shukatunda", sanskrit_name="Shukatunda", mudra_type=MudraType.ASAMYUTA,
                  description="Parrot's beak - ring finger bent from Arala",
                  fingers="Index and ring fingers bent, others extended",
                  usage=["shooting arrow", "spear throwing", "mystery"],
                  viniyoga="Used for shooting an arrow, throwing a spear"),
            Mudra(name="Mushti", sanskrit_name="Mushti", mudra_type=MudraType.ASAMYUTA,
                  description="Fist - all fingers folded, thumb over fingers",
                  fingers="All four fingers curled into palm, thumb over them",
                  usage=["firmness", "grasping", "wrestling", "holding"],
                  viniyoga="Used for steadfastness, grasping the hair, holding things, wrestling"),
            Mudra(name="Shikhara", sanskrit_name="Shikhara", mudra_type=MudraType.ASAMYUTA,
                  description="Spire - thumb raised from Mushti",
                  fingers="Fist with thumb pointing upward",
                  usage=["God of love", "pillar", "saying no", "bow", "silence"],
                  viniyoga="Used for the God of Love, pillar, questioning, bow, silence, embrace, sounding a bell"),
            Mudra(name="Kapittha", sanskrit_name="Kapittha", mudra_type=MudraType.ASAMYUTA,
                  description="Wood apple - index finger bent over thumb in Shikhara",
                  fingers="Fist with index finger curled over extended thumb",
                  usage=["Lakshmi", "Saraswati", "holding flowers", "milking"],
                  viniyoga="Used for Lakshmi, Saraswati, holding flowers, milking cows"),
            Mudra(name="Katakamukha", sanskrit_name="Katakamukha", mudra_type=MudraType.ASAMYUTA,
                  description="Opening in a bracelet - thumb and first two fingers form ring",
                  fingers="Thumb, index, and middle fingers form a ring, others extended",
                  usage=["plucking flowers", "holding necklace", "women", "mirror"],
                  viniyoga="Used for plucking flowers, holding necklace, pulling string of a bow"),
            Mudra(name="Suchi", sanskrit_name="Suchi", mudra_type=MudraType.ASAMYUTA,
                  description="Needle - index finger extended from fist",
                  fingers="Index finger pointing up, rest in fist",
                  usage=["one", "the world", "the sun", "city", "pointing"],
                  viniyoga="Used for the number one, the world, the sun, threatening"),
            Mudra(name="Chandrakala", sanskrit_name="Chandrakala", mudra_type=MudraType.ASAMYUTA,
                  description="Moon digit - thumb extended from Suchi",
                  fingers="Index finger up with thumb extended sideways from fist",
                  usage=["crescent moon", "face"],
                  viniyoga="Used for the crescent moon"),
            Mudra(name="Padmakosha", sanskrit_name="Padmakosha", mudra_type=MudraType.ASAMYUTA,
                  description="Lotus bud - fingers spread and slightly cupped",
                  fingers="All five fingers spread apart and slightly curved inward",
                  usage=["lotus", "fruit", "ball", "mango", "bell", "breast"],
                  viniyoga="Used for lotus bud, bilva fruit, breast, ball, mango, temple bell"),
            Mudra(name="Sarpashirsha", sanskrit_name="Sarpashirsha", mudra_type=MudraType.ASAMYUTA,
                  description="Serpent head - fingers close together, hand cupped downward",
                  fingers="Fingers and thumb close together, hand bent downward at wrist",
                  usage=["snake", "sandal paste", "sprinkling water"],
                  viniyoga="Used for snake movement, giving water, slowness"),
            Mudra(name="Mrigashirsha", sanskrit_name="Mrigashirsha", mudra_type=MudraType.ASAMYUTA,
                  description="Deer head - little and thumb extended, others bent",
                  fingers="Little finger and thumb extended, middle three fingers bent at first joint",
                  usage=["deer", "calling someone", "dress", "fear", "argument"],
                  viniyoga="Used for a deer face, women, calling, fear, discussion"),
            Mudra(name="Simhamukha", sanskrit_name="Simhamukha", mudra_type=MudraType.ASAMYUTA,
                  description="Lion face - middle and ring fingers touch thumb",
                  fingers="Middle and ring fingers touch thumb tip, index and little extended",
                  usage=["lion", "elephant", "lotus", "pearl", "offering"],
                  viniyoga="Used for a lion's face, pearl, worship, incense offering, homa fire"),
            Mudra(name="Kangula", sanskrit_name="Kangula", mudra_type=MudraType.ASAMYUTA,
                  description="Bell - ring finger bent over thumb from Padmakosha",
                  fingers="Ring finger bent touching thumb, other fingers spread and curved",
                  usage=["small bell", "coconut", "betel nut"],
                  viniyoga="Used for fruit like coconut, bell, arecanut"),
            Mudra(name="Alapadma", sanskrit_name="Alapadma", mudra_type=MudraType.ASAMYUTA,
                  description="Fully bloomed lotus - fingers fully spread",
                  fingers="All fingers spread wide apart, slightly curved back",
                  usage=["full moon", "beauty", "lake", "full bloom"],
                  viniyoga="Used for beauty, full moon, pond, circular motion, village"),
            Mudra(name="Chatura", sanskrit_name="Chatura", mudra_type=MudraType.ASAMYUTA,
                  description="Four - from Tripataka with little finger also raised",
                  fingers="All four fingers extended and slightly apart, thumb pressed against palm",
                  usage=["cleverness", "gold", "musk", "grief"],
                  viniyoga="Used for a little, cleverness, gold, musk, grief"),
            Mudra(name="Bhramara", sanskrit_name="Bhramara", mudra_type=MudraType.ASAMYUTA,
                  description="Bee - middle finger bent, index on thumb, others extended",
                  fingers="Index on thumb, middle bent down, ring and little extended",
                  usage=["bee", "parrot", "crane", "cuckoo", "union"],
                  viniyoga="Used for a bee, a parrot, a crane, a wing, a cuckoo"),
            Mudra(name="Hamsasya", sanskrit_name="Hamsasya", mudra_type=MudraType.ASAMYUTA,
                  description="Swan face - index and thumb touch, others extended",
                  fingers="Index finger and thumb tip touching, other three fingers extended",
                  usage=["painting", "garland", "pearl", "jasmine", "tying"],
                  viniyoga="Used for tying the marriage thread, drawing, holding delicate things"),
            Mudra(name="Hamsapaksha", sanskrit_name="Hamsapaksha", mudra_type=MudraType.ASAMYUTA,
                  description="Swan wing - fingers extended and spread, thumb bent",
                  fingers="All four fingers spread wide, thumb pressed to palm",
                  usage=["bridge", "number six"],
                  viniyoga="Used for the number six, building a bridge, covering"),
            Mudra(name="Samdamsha", sanskrit_name="Samdamsha", mudra_type=MudraType.ASAMYUTA,
                  description="Pincers - all fingers and thumb together at tips",
                  fingers="All fingertips and thumb tip touching together pointing up",
                  usage=["offering", "worship", "stomach", "wound"],
                  viniyoga="Used for offering, belly, wound, generosity"),
            Mudra(name="Mukula", sanskrit_name="Mukula", mudra_type=MudraType.ASAMYUTA,
                  description="Bud - all fingertips touching thumb",
                  fingers="All four fingertips meeting at thumb tip forming a bud shape",
                  usage=["water lily", "eating", "the number five"],
                  viniyoga="Used for eating, water lily, the number five"),
            Mudra(name="Tamrachuda", sanskrit_name="Tamrachuda", mudra_type=MudraType.ASAMYUTA,
                  description="Rooster - from Tripataka, ring meets thumb at its base",
                  fingers="Index and middle extended, ring finger curled to thumb base, little extended",
                  usage=["rooster", "crane", "calf"],
                  viniyoga="Used for a rooster, a camel, a crane writing"),
            Mudra(name="Trishula", sanskrit_name="Trishula", mudra_type=MudraType.ASAMYUTA,
                  description="Trident - three fingers up from Mushti, thumb holds ring finger",
                  fingers="Index, middle, little up and apart, thumb holds ring finger down",
                  usage=["trident", "Bilva leaf", "the number three"],
                  viniyoga="Used for trident, Bilva leaf, the number three, tripod"),
        ]

    def _load_samyuta(self) -> list[Mudra]:
        """24 Samyuta (double-hand) hastas."""
        return [
            Mudra(name="Anjali", sanskrit_name="Anjali", mudra_type=MudraType.SAMYUTA,
                  description="Salutation - both Pataka hands joined at palms",
                  fingers="Both palms flat together, fingers pointing up",
                  usage=["greeting gods", "greeting guru", "prayer", "namaste"],
                  viniyoga="At head for gods, at face for guru, at chest for others"),
            Mudra(name="Kapota", sanskrit_name="Kapota", mudra_type=MudraType.SAMYUTA,
                  description="Pigeon - Anjali with fingers slightly parted",
                  fingers="Both Pataka palms together with slight gap between fingers",
                  usage=["accepting", "agreeing", "devotion"],
                  viniyoga="Used for accepting commands, obedience, greeting elders"),
            Mudra(name="Karkata", sanskrit_name="Karkata", mudra_type=MudraType.SAMYUTA,
                  description="Crab - fingers interlocked",
                  fingers="Fingers of both hands interlocked, palms hollow",
                  usage=["stretching", "yawning", "blowing conch", "crowd"],
                  viniyoga="Used for a crowd of women, bending a branch, yawning"),
            Mudra(name="Swastika", sanskrit_name="Swastika", mudra_type=MudraType.SAMYUTA,
                  description="Auspicious cross - both Pataka wrists crossed",
                  fingers="Both open hands crossed at the wrists",
                  usage=["crocodile", "beginning", "denying"],
                  viniyoga="Used for crocodile, opening, denial"),
            Mudra(name="Dola", sanskrit_name="Dola", mudra_type=MudraType.SAMYUTA,
                  description="Swing - both Pataka hands by sides",
                  fingers="Both open palms facing thighs, arms hanging naturally",
                  usage=["starting position", "ease", "quiet standing"],
                  viniyoga="Used for standing position, starting pose"),
            Mudra(name="Pushpaputa", sanskrit_name="Pushpaputa", mudra_type=MudraType.SAMYUTA,
                  description="Flower casket - both Sarpashirsha placed side by side",
                  fingers="Both hands cupped together palms up, side by side",
                  usage=["offering flowers", "receiving", "carrying water"],
                  viniyoga="Used for receiving flowers, water, or offerings"),
            Mudra(name="Utsanga", sanskrit_name="Utsanga", mudra_type=MudraType.SAMYUTA,
                  description="Embrace - both arms crossed over chest",
                  fingers="Arms crossed, hands on opposite shoulders in Mrigashirsha",
                  usage=["embrace", "modesty", "love", "cold"],
                  viniyoga="Used for embracing, shyness, feeling cold"),
            Mudra(name="Shivalinga", sanskrit_name="Shivalinga", mudra_type=MudraType.SAMYUTA,
                  description="Shiva's symbol - one fist inside other cupped hand",
                  fingers="Left hand cupped (Ardhachandra) under right fist (Shikhara)",
                  usage=["Shiva", "linga", "creation"],
                  viniyoga="Used for Shivalinga representation"),
            Mudra(name="Kataka Vardhamanaka", sanskrit_name="Kataka Vardhamanaka", mudra_type=MudraType.SAMYUTA,
                  description="Link of increase - two Katakamukha hands linked",
                  fingers="Both hands in Katakamukha, linked at fingertips",
                  usage=["marriage", "coronation", "worship"],
                  viniyoga="Used for marriage, crowning, consecration"),
            Mudra(name="Kartari Swastika", sanskrit_name="Kartari Swastika", mudra_type=MudraType.SAMYUTA,
                  description="Scissors cross - both Kartarimukha hands crossed at wrists",
                  fingers="Both hands in Kartarimukha, crossed at wrists",
                  usage=["tree branches", "hilltop", "difference"],
                  viniyoga="Used for treetops, mountain peaks"),
            Mudra(name="Shakata", sanskrit_name="Shakata", mudra_type=MudraType.SAMYUTA,
                  description="Cart - both Tripataka hands thumbs interlocked",
                  fingers="Both Tripataka hands interlocked at thumbs",
                  usage=["carrying", "demon", "large body"],
                  viniyoga="Used for representing a demon, large body shape"),
            Mudra(name="Shankha", sanskrit_name="Shankha", mudra_type=MudraType.SAMYUTA,
                  description="Conch - left hand wraps right thumb",
                  fingers="Left hand wraps right fist's raised thumb, left thumb touches right middle finger",
                  usage=["conch shell", "Vishnu", "blowing conch"],
                  viniyoga="Used for blowing conch, calling, Vishnu worship"),
            Mudra(name="Chakra", sanskrit_name="Chakra", mudra_type=MudraType.SAMYUTA,
                  description="Disc - both Ardhachandra hands circle each other",
                  fingers="Both Ardhachandra hands making a circle, fingertips touching",
                  usage=["wheel", "Sudarshana Chakra", "Vishnu"],
                  viniyoga="Used for Vishnu's discus, a wheel"),
            Mudra(name="Samputa", sanskrit_name="Samputa", mudra_type=MudraType.SAMYUTA,
                  description="Casket - one hand cupped inside the other",
                  fingers="One Sarpashirsha hand placed inside the other, edges touching",
                  usage=["concealing", "casket", "jewel box"],
                  viniyoga="Used for hiding something, a casket, a box"),
            Mudra(name="Pasha", sanskrit_name="Pasha", mudra_type=MudraType.SAMYUTA,
                  description="Noose - both hands in Suchi crossed at wrists",
                  fingers="Both index fingers pointing up, wrists crossed, others in fist",
                  usage=["chain", "quarrel", "binding"],
                  viniyoga="Used for a chain, binding, quarrel, anger"),
            Mudra(name="Kilaka", sanskrit_name="Kilaka", mudra_type=MudraType.SAMYUTA,
                  description="Bond - both hands interlocked with little fingers out",
                  fingers="Fingers interlocked, little fingers extended",
                  usage=["affection", "conversation", "close bond"],
                  viniyoga="Used for affection, intimate conversation, closeness"),
            Mudra(name="Matsya", sanskrit_name="Matsya", mudra_type=MudraType.SAMYUTA,
                  description="Fish - one Pataka on back of other, thumbs as fins",
                  fingers="One open palm face down on other palm face up, thumbs extended as fins",
                  usage=["fish", "Matsya avatar", "water creature"],
                  viniyoga="Used for a fish, Vishnu's Matsya avatar"),
            Mudra(name="Kurma", sanskrit_name="Kurma", mudra_type=MudraType.SAMYUTA,
                  description="Tortoise - one cupped hand over another",
                  fingers="Both hands cupped, one placed over the other hiding fingers",
                  usage=["tortoise", "Kurma avatar"],
                  viniyoga="Used for a tortoise, Vishnu's Kurma avatar"),
            Mudra(name="Varaha", sanskrit_name="Varaha", mudra_type=MudraType.SAMYUTA,
                  description="Boar - Ardhachandra over Mushti",
                  fingers="One hand in Ardhachandra placed over other in Mushti",
                  usage=["boar", "Varaha avatar"],
                  viniyoga="Used for a boar, Vishnu's Varaha avatar"),
            Mudra(name="Garuda", sanskrit_name="Garuda", mudra_type=MudraType.SAMYUTA,
                  description="Eagle - thumbs interlocked, fingers spread as wings",
                  fingers="Both palms facing out, thumbs interlocked, fingers spread wide",
                  usage=["Garuda", "eagle", "bird"],
                  viniyoga="Used for Garuda, Vishnu's mount, a large bird"),
            Mudra(name="Nagabandha", sanskrit_name="Nagabandha", mudra_type=MudraType.SAMYUTA,
                  description="Serpent bond - both wrists crossed, Sarpashirsha",
                  fingers="Both hands in Sarpashirsha crossed at wrists",
                  usage=["two serpents", "Naga", "fight"],
                  viniyoga="Used for two serpents, battle between snakes"),
            Mudra(name="Khatva", sanskrit_name="Khatva", mudra_type=MudraType.SAMYUTA,
                  description="Cot - fingers interlocked upward",
                  fingers="Both hands with fingers interlocked, palms facing up",
                  usage=["cot", "bed", "seat", "palanquin"],
                  viniyoga="Used for a couch, seat, throne, palanquin"),
            Mudra(name="Bherunda", sanskrit_name="Bherunda", mudra_type=MudraType.SAMYUTA,
                  description="Pair of birds - both Kapittha touching at wrists",
                  fingers="Both hands in Kapittha, wrists touching",
                  usage=["pair of birds", "couple"],
                  viniyoga="Used for a pair of birds, a loving couple"),
            Mudra(name="Avahittha", sanskrit_name="Avahittha", mudra_type=MudraType.SAMYUTA,
                  description="Dissimulation - one hand crosses over the other at chest",
                  fingers="Pataka hands crossed at chest, one over the other",
                  usage=["looking away", "hiding emotion", "concealment"],
                  viniyoga="Used for averting the face, hiding emotions"),
        ]

    def get_all_mudras(self) -> list[Mudra]:
        return self._mudras

    def get_asamyuta(self) -> list[Mudra]:
        return [m for m in self._mudras if m.mudra_type == MudraType.ASAMYUTA]

    def get_samyuta(self) -> list[Mudra]:
        return [m for m in self._mudras if m.mudra_type == MudraType.SAMYUTA]

    def get_mudra(self, name: str) -> Mudra | None:
        for m in self._mudras:
            if m.name.lower() == name.lower():
                return m
        return None

    def search_by_usage(self, query: str) -> list[Mudra]:
        q = query.lower()
        return [m for m in self._mudras if any(q in u.lower() for u in m.usage)]
